### ISSUE TITLE
4. Contact

### ISSUE THREAD

**Issue by kathp28** [loogart/Project-Mountain#13]
a) The introduction text is incorrect. Their address won't appear on their badge.

b) What do we do for province/state if they come from anywhere but Canada or the US?

c) Idem for zip/postal code

**Comment by loogart** [comment]
a) @kathp28 you're right i copy pasted the text from step #2. Do you have a text I can update this to?
b) good point, the backend logic will have to take care of this feature
c) same as above (b)

**Comment by loogart** [comment]
fixed. https://loogart.github.io/Project-Mountain/registration-step4.html
