### ISSUE TITLE
Your organisation

### ISSUE THREAD

**Issue by T-Diego** [loogart/Project-Mountain#7]
Could we have some sort of validation tool to try to prevent multiple entries for the same company

**Comment by loogart** [comment]
the new proposed solution should let you start typing and providing existing organizations in the dropdown. If the user types a name that doesn't exist, the app should add it automatically as a new organization.

**Comment by loogart** [comment]
done, start typing the letter H for example!

**Comment by T-Diego** [comment]
But now it only gives you those that start with the letter, so if I type Inn… it doesn’t show *the* innolab…

**Comment by loogart** [comment]
Fixed! Used a more solid piece of technology developed by Twitter. Try typing Facebook, Innolab, etc...

https://loogart.github.io/Project-Mountain/registration.html
