### ISSUE TITLE
Webcam/take photo

### ISSUE THREAD

**Issue by TimMorganlive** [loogart/Project-Mountain#8]
Possibility of adding 'take photo' or 'webcam' button next to the 'upload photo' option?

**Comment by loogart** [comment]
Just checked, you can only upload a photo on most social media sites (e.g. Facebook). it's probably safer to stick to something similar for our web app. If you use a mobile phone though, you have the option of taking a photo directly and uploading it to the browser - mobile phones integrate that feature directly. So if we do this onsite and help people register, I suggest we do it via iPads or Android tablets to skip the extra step.
